Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Function to configure clients for NRPE and monitoring
    def configure_client(config, name, ip, memory, clinet_script_path, is_client = true)
        config.vm.define name do |client|

            client.vm.box = "eurolinux-vagrant/centos-stream-9"
            client.vm.hostname = name
            client.vm.network "private_network", ip: ip
            client.vm.boot_timeout = 1500
            client.vm.provider "virtualbox" do |vb|
                    vb.memory = memory
            end
        
            # Install and configure NRPE
            client.vm.provision "shell", path: clinet_script_path, privileged: true
            if is_client
                client.vm.provision "shell", path: "./common/install_nagios_client.sh", privileged: true
            end
        end
    end
    
    
### DB vm  ####
    configure_client(config, "db01", "192.168.56.15", 2048, "./db01_data/main.sh")

### Memcache vm  #### 
    configure_client(config, "mc01", "192.168.56.14", 900, "./mc01_data/main.sh")

### RabbitMQ vm  ####
    configure_client(config, "rmq01", "192.168.56.13", 600, "./rmq01_data/main.sh")

### tomcat vm ###
    configure_client(config, "app01", "192.168.56.12", 4200, "./app01_data/main.sh")

### tomcat vm ###
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.11"
        web01.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.memory = "800"
        end

        # Provision services and NRPE
        web01.vm.provision "shell", path: "./web01_data/main.sh", privileged: true
        web01.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y nagios-nrpe-server nagios-plugins
        echo "allowed_hosts=127.0.0.1,192.168.56.10" >> /etc/nagios/nrpe.cfg
        systemctl enable nagios-nrpe-server && systemctl start nagios-nrpe-server
        ufw allow 5666
        SHELL
    end

### NAGIOS SERVER VM ###
    configure_client(config, "nagiosserver", "192.168.56.10", 1024, "./nagios_server_data/main.sh", false)

end