Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Function to configure clients for NRPE and monitoring
    def configure_client(config, name, ip, memory, clinet_script_path)
        config.vm.define name do |client|

            client.vm.box = "eurolinux-vagrant/centos-stream-9"
            client.vm.hostname = name
            client.vm.network "private_network", ip: ip
            client.vm.provider "virtualbox" do |vb|
                    vb.memory = memory
            end
        
            # Install and configure NRPE
            client.vm.provision "shell", path: clinet_script_path
            client.vm.provision "shell", path: "./common/install_nagios_client.sh"

        end
    end
    
    
### DB vm  ####
    configure_client(config, "db01", "192.168.56.15", 2048, "./db01_data/main.sh")

### Memcache vm  #### 
    configure_client(config, "mc01", "192.168.56.14", 900, "./mc01_data/main.sh")

### RabbitMQ vm  ####
    configure_client(config, "rmq01", "192.168.56.13", 600, "./rmq01_data/main.sh")

### tomcat vm ###
    configure_client(config, "app01", "192.168.56.12", 4200, "./app01_data/main.sh")

### Nginx VM ###
    configure_client(config, "web02", "192.168.56.11", 800, "./web02_data/main.sh")


### NAGIOS SERVER VM ###
    config.vm.define "nagiosserver" do |nagiosserver|
        nagiosserver.vm.box = "bento/ubuntu-20.04"
        nagiosserver.vm.hostname = "nagiosserver"
        nagiosserver.vm.network "private_network", ip: "192.168.56.10"
        nagiosserver.vm.provision "shell", path: "./nagios_server_data/main.sh"
        nagiosserver.vm.boot_timeout = 1200
        nagiosserver.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
        end
    end
end