Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Function to configure clients for NRPE and monitoring
    def configure_client(config, name, ip, memory, vcpu, client_script_path = nil)
        config.vm.define name do |client|
            client.vm.box = "bento/ubuntu-22.04"
            client.vm.hostname = name
            client.vm.network "private_network", ip: ip
            client.vm.boot_timeout = 5000
            client.vm.provider "virtualbox" do |vb|
                vb.memory = memory
                vb.cpus = vcpu
            end
        
            # Install and configure NRPE if a script path is provided
            if client_script_path
                client.vm.provision "shell", path: client_script_path, privileged: true
            end
        end
    end
    
    ### Master VM ###
    configure_client(config, "controlplane", "10.0.0.10", 4096, 5, "./control_plane.sh")

    ### Control 1 ###
    configure_client(config, "node01", "10.0.0.11", 3572, 2, "./worker.sh")

    ### Control 2 ###
    configure_client(config, "node02", "10.0.0.12", 3572, 2, "./worker.sh")

end
