Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

    # Function to configure clients for NRPE and monitoring
    def configure_client(config, name, ip, memory, client_script_path = nil)
        config.vm.define name do |client|
            client.vm.box = "bento/ubuntu-22.04"
            client.vm.hostname = name
            client.vm.network "private_network", ip: ip
            client.vm.provider "virtualbox" do |vb|
                vb.memory = memory
            end
        
            # Install and configure NRPE if a script path is provided
            if client_script_path
                client.vm.provision "shell", path: client_script_path, privileged: true
            end
        end
    end
    
    ### Master VM ###
    configure_client(config, "mastervm", "192.168.56.15", 4096, "./db01_data/main.sh")

    ### Control 1 ###
    configure_client(config, "control1", "192.168.56.14", 2048, "./mc01_data/main.sh")

    ### Control 2 ###
    configure_client(config, "control2", "192.168.56.13", 2048, "./rmq01_data/main.sh")

end
