Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

### DB vm  ####
    config.vm.define "db01" do |db01|


        db01.vm.box = "bento/ubuntu-20.04"
        db01.vm.box_version = "202407.23.0"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provision "shell", path: "./nagios_server_data/main.sh"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end
        
    end

### Memcache vm  #### 
    config.vm.define "mc01" do |mc01|

        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.box_version = "9.0.43"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.14"
        # mc01.vm.provision "shell", path: "./mc01_data/main.sh"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

    end

end