Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

### DB vm  ####
    config.vm.define "nagios_server" do |nagios_server|


        nagios_server.vm.box = "bento/ubuntu-20.04"
        nagios_server.vm.box_version = "202407.23.0"
        nagios_server.vm.hostname = "nagios_server"
        nagios_server.vm.network "private_network", ip: "192.168.56.15"
        nagios_server.vm.provision "shell", path: "./nagios_server_data/main.sh"
        nagios_server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end
        
    end

### Memcache vm  #### 
    config.vm.define "nagios_client" do |nagios_client|

        nagios_client.vm.box = "eurolinux-vagrant/centos-stream-9"
        nagios_client.vm.box_version = "9.0.43"
        nagios_client.vm.hostname = "nagios_client"
        nagios_client.vm.network "private_network", ip: "192.168.56.14"
        nagios_client.vm.provision "shell", path: "./nagios_client_data/main.sh"
        nagios_client.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

    end


    config.vm.define "testr" do |testr|

        testr.vm.box = "eurolinux-vagrant/centos-stream-9"
        testr.vm.box_version = "9.0.43"
        testr.vm.hostname = "testr"
        testr.vm.network "private_network", ip: "192.168.56.14"
        testr.vm.provision "shell", path: "./testr/main.sh"
        testr.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

    end

end