Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true

### DB vm  ####
    config.vm.define "db01" do |db01|

        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.box_version = "9.0.43"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
        config.vm.provision "shell", path: "./db01_data/main.sh"
    end


end